### ISSUE TITLE
Getting "no port targeted" and transparent docking window in 6.9.1

### ISSUE THREAD

**Issue by mattthehearn** [bfishman/Docking-Port-Alignment-Indicator#9] opened 2020-07-09 18:59 UTC
Hello!  I recently upgraded to 6.9.1 (I use CKAN to manage modules) and when I attempt to dock, the Alignment Indicator reads "No Port Targeted" and the window where it would normally show the indicators is transparent.  I downgraded back to 6.8.6 and it works fine.  Let me know if you need more info.  Is it possible this is part of the "Docking port restrictions have been added. When cycling through docking ports,  only docking ports which are compatible with the current vessel are shown. (#4)" fix for 6.9.0?  I didn't try that version but will shortly.

KSP version is 1.9.1.2788.

**Comment by mwerle** [comment] 2020-07-09 22:01
thanks for the report but there's not much we can do to try to reproduce the issue with that description.

logs and exact reproduction steps are required at a minimum, as well as what kind of ports you are trying to dock (stock or mod)

possibly some screenshots (have never seen the docking window transparant before) 

ideally a save game (with no mod requirements) which reproduces the issue (named quick-saves work great)

**Comment by mwerle** [comment] 2020-10-05 15:40
Possibly fixed in https://github.com/bfishman/Docking-Port-Alignment-Indicator/releases/tag/6.9.1.1

**Comment by mwerle** [comment] 2020-11-29 04:34
Closing due to inactivity; please reopen if this is still an issue.

**Closed by mwerle** 2020-11-29 04:34 UTC
